[package]
name = "cached-nix-shell"
version = "0.1.0"
authors = ["Albert Safin <xzfcpw@gmail.com>"]
license = "Unlicense OR MIT"
edition = "2018"

[dependencies]
clap = "2"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellwords = "1"
xdg = "^2.1"
rust-crypto = "^0.2"
