[package]
name = "cached-nix-shell"
version = "0.1.0"
authors = ["Albert Safin <xzfcpw@gmail.com>"]
license = "Unlicense OR MIT"
edition = "2018"

[dependencies]
itertools = "0.8"
nix = "0.16"
regex = "1"
rust-crypto = "^0.2"
serde_json = "1.0"
shellwords = "1"
tempfile = "3.1.0"
xdg = "^2.1"
